<div style="height: 100vh; background-image: url(<?= "/img/" . $recipe->picture ?>); background-size: cover;">
    <div class = "container">
        <div class = "row" style="background: #ccc; width: 50%; padding: 20px 5px 10px 20px; opacity: .8;">

            <div><h1 style="text-align: left;"><?= $recipe->name ?></h1><span style="line-height: 1.2; text-align: right; color: #fff; font-size: 2rem;"><?= $recipe->time ?> mins</span></div>
        </div>
        <div class="row" style="background: #ccc; width: 50%; height: 100%; margin-top: 20px; line-height: 1.2; padding: 10px 5px 10px 20px; opacity: .8;">
            <p style="padding: 20px 5px 10px 20px; line-height: 1.2; opacity: .8; font-size: 30px;">
                Ingredients:
            
                <span style="font-size: 20px;"><?= $recipe->ingredients ?></span>
            </p>
        </div>
        <div class="row" style="background: #ccc; width: 50%; height: 100%; margin-top: 20px; line-height: 1.2; padding: 20px 5px 10px 20px; opacity: .8;">
            <p style="line-height: 1.2; padding: 20px 5px 10px 20px; opacity: .8; font-size: 30px;">
                Instructions:
                <span style="font-size: 20px;"><?= $recipe->instructions ?></span>
            </p>
        </div>
    </div>
</div>
