<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?= $title ?> | Tasty Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row">
            <!--navbar -->
            <div class="col-sm-12" style="margin-bottom:20px;">
                <nav class="navbar navbar-dark bg-dark">
                    <a class="navbar-brand" href="http://lmichelle.techlaunch.io/tasty/recipes">TASTY.APP</a>
                </nav>
            </div>

            <!--menu -->
            <div class="col-sm-3">
                <div class="text-center">
                    <img style="height:200px;" class="rounded img-fluid" src="<?= "/tasty/public/img/" . $user->picture ?>" alt="Profile Image">
                    <p><b><?= $user->name; ?></b> <small><?= $user->email; ?></small></p>
                </div>
                <hr/>
                <div class="menu">
                    <a class="dropdown-item <?= $page=="recipes" ? "active" : "" ?>" href="/tasty/admin/recipes">List of recipes</a>
                    <a class="dropdown-item <?= $page=="add" ? "active" : "" ?>" href="/tasty/admin/add">Add a recipe</a>
                    <a class="dropdown-item" href="/tasty/login/logout">Logout</a>
                </div>
            </div>

            <!--content -->
            <div class="col-sm-9">
                <h1><?= $title ?></h1>
                <br/>
                <?= $this->getContent() ?>
            </div>
        </div>
    </div>
</body>
</html>
