<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Tasty Home</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <!--navbar -->
            <div class="col-sm-12">
                <nav class="navbar navbar-dark bg-dark">
                    <a class="navbar-brand" href="/recipes">TASTY.APP (Home)</a>
                    <a class="navbar-brand" href="/login">Login</a>
                </nav>
            </div>
        </div>

        <!--content -->
        <?= $this->getContent() ?>
    </div>
</body>
</html>
