<?php if($error) { ?>
    <div class="alert alert-danger" role="alert">Wrong username or Password</div>
<?php } ?>

<form action="/tasty/login/submit" method="post">
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" name="email" class="form-control" id="email" />
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" name="password" class="form-control" id="password" />
    </div>

    <input class="btn btn-primary" type="submit" value="Login" />
</form>

<div style="padding-top: 30px;">Don't have an account? <a href="/tasty/login/signup">Sign Up</a></div>
